# Generated by Django 6.0.7 on 2026-08-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('manager', 'Менеджер отеля'), ('admin', 'Администратор')], default='guest', max_length=20),
        ),
    ]
