# Generated by Django 6.0.7 on 2026-08-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_phone_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_email',
            field=models.BooleanField(default=False),
        ),
    ]
