# Generated by Django 6.0.7 on 2026-08-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recomend_city',
            field=models.CharField(blank=True, default='Укажите город', max_length=25),
        ),
    ]
