# Generated by Django 6.0.7 on 2026-08-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_recomend_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='recomend_city',
            field=models.CharField(choices=[('moscow', 'Москва'), ('saint_petersburg', 'Санкт-Петербург'), ('novosibirsk', 'Новосибирск'), ('ekaterinburg', 'Екатеринбург'), ('kazan', 'Казань'), ('nizhny_novgorod', 'Нижний Новгород'), ('chelyabinsk', 'Челябинск'), ('samara', 'Самара'), ('omsk', 'Омск'), ('rostov_on_don', 'Ростов-на-Дону')], default='Укажите город'),
        ),
    ]
