# Generated by Django 6.0.7 on 2026-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_recomend_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correct_profile',
            field=models.BooleanField(default=False),
        ),
    ]
