# Generated by Django 6.0.7 on 2026-08-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_customuser_correct_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
