# Generated by Django 6.0.7 on 2026-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_app', '0002_hotel_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='img',
            field=models.ImageField(blank=True, default='meida_img/logo_arenda.png', null=True, upload_to='media/'),
        ),
    ]
