# Generated by Django 6.0.7 on 2026-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_app', '0004_alter_hotel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='like',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
