# Generated by Django 6.0.7 on 2026-09-11 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_app', '0005_hotel_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='like',
        ),
        migrations.CreateModel(
            name='FavoritHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=255)),
                ('like', models.ManyToManyField(blank=True, related_name='liked_hotels_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
