# Generated by Django 6.0.7 on 2026-09-11 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda_app', '0006_remove_hotel_like_favorithotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_hotels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='FavoritHotel',
        ),
    ]
